fail_fast: true
repos:
  - repo: local
    hooks:
      - id: check-unstaged
        name: block-unstaged-changes
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
        description: Blocks commit if there are unstaged changes to prevent pre-commit stash conflicts.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^venv/
      - id: ruff-format
        exclude: ^venv/

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--line-length=100]
        exclude: ^venv/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["polla_app", "tests"]

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        args: ["-q"]
        always_run: true
