name: Check CREDENTIALS environment variable

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Check CREDENTIALS environment variable
        run: |
          python -c "import os; credentials = os.environ['CREDENTIALS']; print(credentials)"
