name: Sync main to master

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: sync-main-to-master
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push main to master
        run: |
          # Create/update remote 'master' to mirror current 'main'
          git push --force-with-lease origin HEAD:refs/heads/master

