name: Test

on:
  schedule:
    - cron: '0 1 * * Mon,Wed,Fri'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
    steps:
    - uses: actions/checkout@v3.4.0
    - name: Set up JSON key
      run: echo "${{ secrets.CREDENTIALS }}" > service-account.json
    - run: pip install -r requirements.txt
    - run: python main.py


