name: Polla.cl Prize Updater

on:
  schedule:
    - cron: '0 2 * * *'  # 02:00 UTC daily
  workflow_dispatch:

jobs:
  update-prizes:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome and dependencies
      run: |
        # First update package lists
        sudo apt-get update -qq

        # Install Chrome dependencies first
        sudo apt-get install -y --no-install-recommends \
          libasound2 \
          libnss3 \
          libgbm1 \
          libxdamage1 \
          libxcomposite1 \
          libxcursor1 \
          libxi6 \
          libxtst6

        # Install Chrome
        sudo apt-get install -y wget
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/googlechrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update -qq
        sudo apt-get install -y google-chrome-stable

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.10.0 google-api-python-client==2.92.0 tenacity==8.2.3

    - name: Run prize updater
      env:
        CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python -u main.py

    - name: Cleanup
      if: always()
      run: |
        sudo pkill -f chrome || true
        sudo rm -rf /tmp/.com.google.Chrome.* || true