name: Polla Prize Updater

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -qO chrome.deb "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.96-1_amd64.deb"
        sudo dpkg -i chrome.deb || sudo apt-get install -yf
        rm chrome.deb

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          libnss3 libx11-6 libxcb1 libx11-xcb1 libxcomposite1 \
          libxcursor1 libxdamage1 libxext6 libxi6 libxtst6 \
          libxrandr2 libxss1 libatk-bridge2.0-0 \
          libgtk-3-0 libgbm1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.10.0 beautifulsoup4==4.12.2 google-api-python-client==2.92.0 webdriver-manager==3.8.6

    - name: Run updater
      env:
        CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python -u main.py