name: Update Prizes

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-prizes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run script
        env:
          CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python -u main.py
        timeout-minutes: 5

      - name: List workspace files (debug)
        if: always()
        run: ls -la

      - name: Upload debug screenshot artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*_failure_*.png"
