name: Verify Secrets

on:
  workflow_dispatch:

jobs:
  verify-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verify GOOGLE_SHEETS_CREDENTIALS
        run: |
          if [ -n "$GOOGLE_SHEETS_CREDENTIALS" ]; then
            echo "Secret exists and is not empty"
            echo "Secret length: ${#GOOGLE_SHEETS_CREDENTIALS}"
            echo "First character: ${GOOGLE_SHEETS_CREDENTIALS:0:1}"
            echo "Last character: ${GOOGLE_SHEETS_CREDENTIALS: -1}"
            if [[ ${GOOGLE_SHEETS_CREDENTIALS:0:1} == "{" && ${GOOGLE_SHEETS_CREDENTIALS: -1} == "}" ]]; then
              echo "✅ Secret appears to be valid JSON"
            else
              echo "❌ Secret does not appear to be valid JSON"
            fi
          else
            echo "❌ Secret is empty"
          fi
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

      - name: Verify GOOGLE_SPREADSHEET_ID
        run: |
          if [ -n "$GOOGLE_SPREADSHEET_ID" ]; then
            echo "GOOGLE_SPREADSHEET_ID is set (length: ${#GOOGLE_SPREADSHEET_ID})"
          else
            echo "❌ GOOGLE_SPREADSHEET_ID is empty"
          fi
        env:
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
