name: Verify Secret

on:
  workflow_dispatch:

jobs:
  verify-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Secret Content
        run: |
          if [ -n "$GOOGLE_CREDENTIALS" ]; then
            echo "Secret exists and is not empty"
            echo "Secret length: ${#GOOGLE_CREDENTIALS}"
            echo "First character: ${GOOGLE_CREDENTIALS:0:1}"
            echo "Last character: ${GOOGLE_CREDENTIALS: -1}"
            if [[ ${GOOGLE_CREDENTIALS:0:1} == "{" && ${GOOGLE_CREDENTIALS: -1} == "}" ]]; then
              echo "✅ Secret appears to be valid JSON"
            else
              echo "❌ Secret does not appear to be valid JSON"
            fi
          else
            echo "❌ Secret is empty"
          fi
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}